#!/bin/bash

#fg_4hy_30%
time python3 compress_classifier.py --arch resnet20_cifar  --dataset cifar100 ../../../datasets/cifar-100-python/ -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_fg_4hy_30spa.yaml --resume-from=.logs/resnet20_cifar100_dense___2020.05.24-221614/resnet20_cifar100_dense_best.pth.tar --reset-optimizer --vs=0 -n resnet20_cifar100_fg_4hy_30spa --gpus 0 &

#fg_4hy_50%
time python3 compress_classifier.py --arch resnet20_cifar  --dataset cifar100 ../../../datasets/cifar-100-python/ -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_fg_4hy_50spa.yaml --resume-from=.logs/resnet20_cifar100_dense___2020.05.24-221614/resnet20_cifar100_dense_best.pth.tar --reset-optimizer --vs=0 -n resnet20_cifar100_fg_4hy_50spa --gpus 1 &

#fg_4h
time python3 compress_classifier.py --arch resnet20_cifar  --dataset cifar100 ../../../datasets/cifar-100-python/ -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_fg_4hy_70spa.yaml --resume-from=.logs/resnet20_cifar100_dense___2020.05.24-221614/resnet20_cifar100_dense_best.pth.tar --reset-optimizer --vs=0 -n resnet20_cifar100_fg_4hy_75spa --gpus 2 &
