#!/bin/bash

#ft_30%
time python3 compress_classifier.py --arch resnet20_cifar --dataset cifar100  ../../../datasets/cifar-100-python/ -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_30spa.yaml --resume-from=./logs/resnet20_cifar100_dense___2020.05.24-221614/resnet20_cifar100_dense_best.pth.tar --reset-optimizer --vs=0 -n resnet20_cifar100_ft_30spa --gpus 0 &

#ft_50%
time python3 compress_classifier.py --arch resnet20_cifar --dataset cifar100 ../../../datasets/cifar-100-python/ -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_50spa.yaml --resume-from=./logs/resnet20_cifar100_dense___2020.05.24-221614/resnet20_cifar100_dense_best.pth.tar --reset-optimizer --vs=0 -n resnet20_cifar100_ft_50spa --gpus 1 &

#ft_75%
time python3 compress_classifier.py --arch resnet20_cifar --dataset cifar100 ../../../datasets/cifar-100-python/ -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_75spa.yaml --resume-from=./logs/resnet20_cifar100_dense___2020.05.24-221614/resnet20_cifar100_dense_best.pth.tar --reset-optimizer --vs=0 -n resnet20_cifar100_ft_75spa --gpus 2 &
