#!/bin/bash

#hy_30%
time python3 compress_classifier.py --arch resnet20_cifar  ../../../data.cifar10 -p=50 --lr=0.3 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_30spa.yaml --resume-from=./logs/resnet20_fg_4hy_30spa___2020.05.23-171232/resnet20_fg_4hy_30spa_best.pth.tar --reset-optimizer --vs=0 -n resnet20_hy_30spa_from30fg --gpus 0 &
time python3 compress_classifier.py --arch resnet20_cifar  ../../../data.cifar10 -p=50 --lr=0.3 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_30spa.yaml --resume-from=./logs/resnet20_fg_4hy_50spa___2020.05.23-172923/resnet20_fg_4hy_50spa_best.pth.tar --reset-optimizer --vs=0 -n resnet20_hy_30spa_from50fg --gpus 0 &
time python3 compress_classifier.py --arch resnet20_cifar  ../../../data.cifar10 -p=50 --lr=0.3 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_30spa.yaml --resume-from=./logs/resnet20_fg_4hy_70spa___2020.05.23-174612/resnet20_fg_4hy_70spa_best.pth.tar --reset-optimizer --vs=0 -n resnet20_hy_30spa_from70fg --gpus 0 &


#hy_50%
time python3 compress_classifier.py --arch resnet20_cifar  ../../../data.cifar10 -p=50 --lr=0.3 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_50spa.yaml --resume-from=./logs/resnet20_fg_4hy_30spa___2020.05.23-171232/resnet20_fg_4hy_30spa_best.pth.tar --reset-optimizer --vs=0 -n resnet20_ft_50spa_from30fg --gpus 1 &
time python3 compress_classifier.py --arch resnet20_cifar  ../../../data.cifar10 -p=50 --lr=0.3 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_50spa.yaml --resume-from=./logs/resnet20_fg_4hy_50spa___2020.05.23-172923/resnet20_fg_4hy_50spa_best.pth.tar --reset-optimizer --vs=0 -n resnet20_ft_50spa_from50fg --gpus 1 &
time python3 compress_classifier.py --arch resnet20_cifar  ../../../data.cifar10 -p=50 --lr=0.3 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_50spa.yaml --resume-from=./logs/resnet20_fg_4hy_70spa___2020.05.23-174612/resnet20_fg_4hy_70spa_best.pth.tar --reset-optimizer --vs=0 -n resnet20_ft_50spa_from70fg --gpus 1 &



#hy_75%
time python3 compress_classifier.py --arch resnet20_cifar  ../../../data.cifar10 -p=50 --lr=0.3 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_75spa.yaml --resume-from=./logs/resnet20_fg_4hy_30spa___2020.05.23-171232/resnet20_fg_4hy_30spa_best.pth.tar --reset-optimizer --vs=0 -n resnet20_ft_75spa_from30fg --gpus 2 &
time python3 compress_classifier.py --arch resnet20_cifar  ../../../data.cifar10 -p=50 --lr=0.3 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_75spa.yaml --resume-from=./logs/resnet20_fg_4hy_50spa___2020.05.23-172923/resnet20_fg_4hy_50spa_best.pth.tar --reset-optimizer --vs=0 -n resnet20_ft_75spa_from50fg --gpus 2 &
time python3 compress_classifier.py --arch resnet20_cifar  ../../../data.cifar10 -p=50 --lr=0.3 --epochs=180 --compress=../agp-pruning/myyaml/resnet/resnet20_ft_noslim_75spa.yaml --resume-from=./logs/resnet20_fg_4hy_70spa___2020.05.23-174612/resnet20_fg_4hy_70spa_best.pth.tar --reset-optimizer --vs=0 -n resnet20_ft_75spa_from70fg --gpus 2 &