#!/bin/bash

#fg_4hy_30%
time python3 compress_classifier.py --arch vgg16_cifar  --dataset cifar100 ../../../datasets/cifar-100-python -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_fg_4hy_30spa.yaml --resume-from=./logs/vgg16_cifar100_dense___2020.05.25-150352/vgg16_cifar100_dense_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar100_fg_4hy_30spa --gpus 0 &

#fg_4hy_50%
time python3 compress_classifier.py --arch vgg16_cifar  --dataset cifar100 ../../../datasets/cifar-100-python -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_fg_4hy_50spa.yaml --resume-from=./logs/vgg16_cifar100_dense___2020.05.25-150352/vgg16_cifar100_dense_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar100_fg_4hy_50spa --gpus 1 &

#fg_4hy_70%
time python3 compress_classifier.py --arch vgg16_cifar  --dataset cifar100 ../../../datasets/cifar-100-python -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_fg_4hy_75spa.yaml --resume-from=./logs/vgg16_cifar100_dense___2020.05.25-150352/vgg16_cifar100_dense_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar100_fg_4hy_75spa --gpus 2 &
