#!/bin/bash

#hy_30%
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_30spa.yaml --resume-from=./vgg16_cifar_logs/vgg16_cifar10_fg_4hy_30spa___2020.05.25-134023/vgg16_cifar10_fg_4hy_30spa_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_hy_30spa_from30fg --gpus 0 &
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_30spa.yaml --resume-from=./vgg16_cifar_logs/vgg16_cifar10_fg_4hy_50spa___2020.05.25-134023/vgg16_cifar10_fg_4hy_50spa_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_hy_30spa_from50fg --gpus 0 &
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_30spa.yaml --resume-from=./vgg16_cifar_logs/vgg16_cifar10_fg_4hy_75spa___2020.05.25-134023/vgg16_cifar10_fg_4hy_75spa_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_hy_30spa_from70fg --gpus 0 &


#hy_50%
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_50spa.yaml --resume-from=./vgg16_cifar_logs/vgg16_cifar10_fg_4hy_30spa___2020.05.25-134023/vgg16_cifar10_fg_4hy_30spa_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_hy_50spa_from30fg --gpus 1 &
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_50spa.yaml --resume-from=./vgg16_cifar_logs/vgg16_cifar10_fg_4hy_50spa___2020.05.25-134023/vgg16_cifar10_fg_4hy_50spa_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_hy_50spa_from50fg --gpus 1 &
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_50spa.yaml --resume-from=./vgg16_cifar_logs/vgg16_cifar10_fg_4hy_75spa___2020.05.25-134023/vgg16_cifar10_fg_4hy_75spa_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_hy_50spa_from70fg --gpus 1 &



#hy_75%
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_75spa.yaml --resume-from=./vgg16_cifar_logs/vgg16_cifar10_fg_4hy_30spa___2020.05.25-134023/vgg16_cifar10_fg_4hy_30spa_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_hy_75spa_from30fg --gpus 2 &
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_75spa.yaml --resume-from=./vgg16_cifar_logs/vgg16_cifar10_fg_4hy_50spa___2020.05.25-134023/vgg16_cifar10_fg_4hy_50spa_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_hy_75spa_from50fg --gpus 2 &
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_75spa.yaml --resume-from=./vgg16_cifar_logs/vgg16_cifar10_fg_4hy_75spa___2020.05.25-134023/vgg16_cifar10_fg_4hy_75spa_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_hy_75spa_from70fg --gpus 2 &