#!/bin/bash

#ft_30%
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_30spa.yaml --resume-from=./logs/vgg16_cifar10_dense___2020.05.25-114025/vgg16_cifar10_dense_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_ft_30spa --gpus 0 &

#ft_50%
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_50spa.yaml --resume-from=./logs/vgg16_cifar10_dense___2020.05.25-114025/vgg16_cifar10_dense_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_ft_50spa --gpus 1 &

#ft_75%
time python3 compress_classifier.py --arch vgg16_cifar  ../../../datasets/data.cifar10 -p=50 --lr=0.01 --epochs=180 --compress=../agp-pruning/myyaml/vgg16/vgg16_cifar_agp_ft_noslim_75spa.yaml --resume-from=./logs/vgg16_cifar10_dense___2020.05.25-114025/vgg16_cifar10_dense_best.pth.tar --reset-optimizer --vs=0 -n vgg16_cifar10_ft_75spa --gpus 2 &
